### ISSUE TITLE
Incluir os tutoriais em uma página web dedicada ao 4noobs

### ISSUE THREAD

**Issue by lucalves** [he4rt/4noobs#1]
Olá pessoal, tudo bem?

Estive dando uma olhada no repositório e vi que é muito interessante, visto que trata de várias categorias relacionadas ao mundo da tecnologia para iniciantes.

Com isso, acredito que a ideia de tornar isso um site com deploy automático dos tutoriais inseridos no repositório diretamente no site.

O que acham?

**Comment by danilomacb** [comment]
> Olá pessoal, tudo bem?
> 
> Estive dando uma olhada no repositório e vi que é muito interessante, visto que trata de várias categorias relacionadas ao mundo da tecnologia para iniciantes.
> 
> Com isso, acredito que a ideia de tornar isso um site com deploy automático dos tutoriais inseridos no repositório diretamente no site.
> 
> O que acham?

Eu to trabalhando num projeto assim, ainda tem algumas coisas pra fazer, como a responsividade, mas o projeto ja ta começando a tomar forma, vc pode dar uma olhada nele aqui:

https://4noobs.netlify.app/

link do repo:

https://github.com/danilomacb/4noobs-web
