### ISSUE TITLE
Linux4noobs

### ISSUE THREAD

**Issue by FelipeSandes** [he4rt/4noobs#103]
É possível contribuir com o Linux4noobs ?
Se sim é só fazer um fork e dar continuidade ?

**Comment by zoldyzdk** [comment]
Boa noite Primo, fica a vontade pra contribuir com esse projeto ou qualquer outro aqui da comunidade!
Acredito que já tenhas visto que em cada 4noobs tem esse passo a passo aqui para quem quiser contribuir, só seguir e sucesso:

![Como contribuir 4noobs](https://user-images.githubusercontent.com/90076846/218609882-fa815e9a-d046-4e1f-9736-ad56be132983.png)
