### ISSUE TITLE
Posso contribuir para o projeto com uma linguagem própria?

### ISSUE THREAD

**Issue by RodrigoDornelles** [he4rt/4noobs#48]
Não está documentado sobre os critérios de como deve ser o tutorial, apenas um pequeno exemplo, tenho algumas duvidas.

* Eu desenvolvi uma linguagem de programação chamada [3BC Lang](https://3bc-lang.org), caberia um tutorial 4noobs?

* Se sim, deve ser na README.md? o meu projeto é um monorepo com código fonte, testes unitários, documentação, pagina web, futuramente também binds e IDE. penso em dedicar uma pagina na documentação para a comunidade he4rt.

* Pode colocar links externos de guias mais avançados no tutorial, para quem quiser se aprofundar ?

**Comment by kjkGustavo** [comment]
Boa tarde! 👋
Desde de já obrigado pela a contribuição com a comunidade! :purple_heart: 

1. Claro, qualquer conteúdo é bem vindo.
2. Seguindo nosso padrão: É sempre bom criar um novo repositório seguindo [essa base](https://github.com/he4rt/4noobs/tree/master/examples).
3. É legal deixa sempre no final para algum complemento. Mas a ideia do 4noobs é ser um conteúdo de introdução e não uma "documentação" com muitas informações.
