### ISSUE TITLE
Sugestão: IDE

### ISSUE THREAD

**Issue by Bernardo-Prado** [he4rt/4noobs#70]
Acho que seria interessante mostrar as variedades de IDEs. Por exemplo, mostrar que pro Python existe o Pycharm que é voltado exclusivamente para o Python, e dar rápidas explicações sobre cada IDE apresentada. Desta forma, os desenvolvedores iniciantes iriam descobrir novas IDEs e quem sabe até migrar para uma do interesse dela.

**Comment by teckscam** [comment]
Boas. 
Que sugere um complemento á pagina wiki ou algo com conteudo mais detalhado e atualizado ?
Segue links do que existe e que na minha sincera opinião deveria ser melhorado e atualizado.
https://wiki.python.org/moin/IntegratedDevelopmentEnvironments

**Comment by Rychillie** [comment]
Acho uma ótima ideia, acrescentando o VSCode poderia ser apresentado como realizar configurações e até a construção de plugins/themes.

Acredito que poderia colaborar muito falando sobre o Codesandbox, IDE na web e mobile que utilizo diariamente.
